# Generated by Django 3.2.4 on 2021-06-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('name', models.CharField(max_length=100, verbose_name='Vaga')),
                ('salary', models.CharField(choices=[('vl', 'Até R$1000'), ('l', 'De R$1000 a R$2000'), ('m', 'De R$2000 a R$3000'), ('h', 'Acima de R$3000')], max_length=2, verbose_name='Salário')),
                ('requirements', models.CharField(max_length=100, verbose_name='Requisitos')),
                ('min_education', models.CharField(choices=[('EF', 'Fundamental'), ('EM', 'Médio'), ('T', 'Técnico'), ('S', 'Superior'), ('M', 'Mestrado/Pós/MBA'), ('D', 'Doutorado')], max_length=2, verbose_name='Escolaridade Mínima')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
