# Generated by Django 3.2.4 on 2021-06-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('surname', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.IntegerField(max_length=11, verbose_name='Número de Telefone - Apenas Números')),
                ('sal_claim', models.CharField(choices=[('VL', 'Até R$1000'), ('L', 'De R$1000 a R$2000'), ('M', 'De R$2000 a R$3000'), ('H', 'Acima de R$3000')], max_length=2, verbose_name='Pretensão Salarial')),
                ('education', models.CharField(choices=[('EF', 'Fundamental'), ('EM', 'Médio'), ('T', 'Técnico'), ('S', 'Superior'), ('M', 'Mestrado/Pós/MBA'), ('D', 'Doutorado')], max_length=2, verbose_name='Última Escolaridade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.CharField(choices=[('VL', 'Até R$1000'), ('L', 'De R$1000 a R$2000'), ('M', 'De R$2000 a R$3000'), ('H', 'Acima de R$3000')], max_length=2, verbose_name='Salário'),
        ),
    ]
