# Generated by Django 3.2.4 on 2021-06-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210617_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(verbose_name='Número de Telefone - Apenas Números'),
        ),
    ]
