# Generated by Django 3.2.4 on 2021-06-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.CharField(choices=[('Até 1000', 'Até R$1000'), ('1000 - 2000', 'De R$1000 a R$2000'), ('2000 - 3000', 'De R$2000 a R$3000'), ('Acima de 3000', 'Acima de R$3000')], max_length=13, verbose_name='Salário'),
        ),
    ]
