# Generated by Django 3.2.4 on 2021-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210617_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='application',
            field=models.CharField(choices=[('Python programmer', 'Python programmer'), ('Python Internship', 'Python Internship'), ('Administer', 'Administer')], max_length=100, verbose_name='Vaga Selecionada'),
        ),
    ]
