# Generated by Django 3.2.4 on 2021-06-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_candidate_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='application',
            field=models.CharField(choices=[], max_length=100, verbose_name='Vaga Selecionada'),
        ),
    ]
